export const SHADOW_CAPABLE_SPECIES = [
  'Abomasnow',
  'Abra',
  'Absol',
  'Accelgor',
  'Aerodactyl',
  'Aggron',
  'Aipom',
  'Alakazam',
  'Altaria',
  'Amaura',
  'Ambipom',
  'Amoonguss',
  'Ampharos',
  'Annihilape',
  'Anorith',
  'Araquanid',
  'Arbok',
  'Arcanine',
  'Archen',
  'Archeops',
  'Armaldo',
  'Aron',
  'Articuno',
  'Aurorus',
  'Bagon',
  'Baltoy',
  'Banette',
  'Barboach',
  'Bastiodon',
  'Bayleef',
  'Beedrill',
  'Beldum',
  'Bellossom',
  'Bellsprout',
  'Bewear',
  'Bibarel',
  'Bidoof',
  'Blastoise',
  'Blaziken',
  'Blitzle',
  'Boldore',
  'Braixen',
  'Bulbasaur',
  'Bunnelby',
  'Butterfree',
  'Cacnea',
  'Cacturne',
  'Camerupt',
  'Carracosta',
  'Carvanha',
  'Caterpie',
  'Chandelure',
  'Charizard',
  'Charjabug',
  'Charmander',
  'Charmeleon',
  'Chesnaught',
  'Chespin',
  'Chikorita',
  'Chimchar',
  'Claydol',
  'Cloyster',
  'Cofagrigus',
  'Combusken',
  'Conkeldurr',
  'Corphish',
  'Cradily',
  'Cranidos',
  'Crawdaunt',
  'Cresselia',
  'Croagunk',
  'Crobat',
  'Croconaw',
  'Crustle',
  'Cubone',
  'Cyndaquil',
  'Darkrai',
  'Darmanitan',
  'Darumaka',
  'Deino',
  'Delibird',
  'Delphox',
  'Dewott',
  'Dewpider',
  'Dialga',
  'Diggersby',
  'Diglett',
  'Donphan',
  'Dragonair',
  'Dragonite',
  'Drapion',
  'Dratini',
  'Drifblim',
  'Drifloon',
  'Drilbur',
  'Drowzee',
  'Ducklett',
  'Dugtrio',
  'Duosion',
  'Dusclops',
  'Dusknoir',
  'Duskull',
  'Dwebble',
  'Ekans',
  'Electabuzz',
  'Electivire',
  'Electrike',
  'Electrode',
  'Emboar',
  'Empoleon',
  'Entei',
  'Escavalier',
  'Excadrill',
  'Exeggcute',
  'Exeggutor',
  'Exploud',
  'Farfetch’d',
  'Feebas',
  'Fennekin',
  'Feraligatr',
  'Ferroseed',
  'Ferrothorn',
  'Flaaffy',
  'Fletchinder',
  'Fletchling',
  'Flygon',
  'Foongus',
  'Forretress',
  'Froakie',
  'Frogadier',
  'Froslass',
  'Gabite',
  'Gallade',
  'Galvantula',
  'Garbodor',
  'Garchomp',
  'Gardevoir',
  'Gastly',
  'Gengar',
  'Geodude',
  'Gible',
  'Gigalith',
  'Girafarig',
  'Giratina',
  'Glalie',
  'Glameow',
  'Gligar',
  'Gliscor',
  'Gloom',
  'Golbat',
  'Golduck',
  'Golem',
  'Golett',
  'Golurk',
  'Gothita',
  'Gothitelle',
  'Gothorita',
  'Granbull',
  'Graveler',
  'Greninja',
  'Grimer',
  'Grotle',
  'Groudon',
  'Grovyle',
  'Growlithe',
  'Grubbin',
  'Grumpig',
  'Gurdurr',
  'Gyarados',
  'Hariyama',
  'Haunter',
  'Heatran',
  'Heliolisk',
  'Helioptile',
  'Hippopotas',
  'Hippowdon',
  'Hitmonchan',
  'Hitmonlee',
  'Hitmontop',
  'Ho-Oh',
  'Honchkrow',
  'Hoppip',
  'Horsea',
  'Houndoom',
  'Houndour',
  'Hydreigon',
  'Hypno',
  'Infernape',
  'Inkay',
  'Ivysaur',
  'Joltik',
  'Jumpluff',
  'Kadabra',
  'Kakuna',
  'Karrablast',
  'Kingdra',
  'Kingler',
  'Kirlia',
  'Koffing',
  'Krabby',
  'Kyogre',
  'Lairon',
  'Lampent',
  'Landorus',
  'Lapras',
  'Larvitar',
  'Latias',
  'Latios',
  'Ledian',
  'Ledyba',
  'Liepard',
  'Lileep',
  'Linoone',
  'Litwick',
  'Loudred',
  'Lugia',
  'Luxio',
  'Luxray',
  'Machamp',
  'Machoke',
  'Machop',
  'Magikarp',
  'Magmar',
  'Magmortar',
  'Magnemite',
  'Magneton',
  'Magnezone',
  'Makuhita',
  'Malamar',
  'Mamoswine',
  'Manectric',
  'Mankey',
  'Mareep',
  'Marowak',
  'Marshtomp',
  'Mawile',
  'Meganium',
  'Meowth',
  'Metagross',
  'Metang',
  'Metapod',
  'Mewtwo',
  'Mightyena',
  'Milotic',
  'Misdreavus',
  'Mismagius',
  'Moltres',
  'Monferno',
  'Morelull',
  'Mudkip',
  'Muk',
  'Murkrow',
  'Natu',
  'Nidoking',
  'Nidoqueen',
  'Nidoran♀',
  'Nidoran♂',
  'Nidorina',
  'Nidorino',
  'Ninetales',
  'Nosepass',
  'Numel',
  'Nuzleaf',
  'Obstagoon',
  'Oddish',
  'Omanyte',
  'Omastar',
  'Onix',
  'Oshawott',
  'Palkia',
  'Patrat',
  'Persian',
  'Phanpy',
  'Phantump',
  'Pidgeot',
  'Pidgeotto',
  'Pidgey',
  'Pidove',
  'Pignite',
  'Pikipek',
  'Piloswine',
  'Pineco',
  'Pinsir',
  'Piplup',
  'Politoed',
  'Poliwag',
  'Poliwhirl',
  'Poliwrath',
  'Ponyta',
  'Poochyena',
  'Porygon',
  'Porygon-Z',
  'Porygon2',
  'Primeape',
  'Prinplup',
  'Probopass',
  'Psyduck',
  'Pupitar',
  'Purrloin',
  'Purugly',
  'Quagsire',
  'Quilava',
  'Quilladin',
  'Qwilfish',
  'Raikou',
  'Ralts',
  'Rampardos',
  'Rapidash',
  'Raticate',
  'Rattata',
  'Regice',
  'Regigigas',
  'Regirock',
  'Registeel',
  'Reuniclus',
  'Rhydon',
  'Rhyhorn',
  'Rhyperior',
  'Roggenrola',
  'Sableye',
  'Salamence',
  'Samurott',
  'Sandshrew',
  'Sandslash',
  'Sawk',
  'Sceptile',
  'Scizor',
  'Scolipede',
  'Scyther',
  'Seadra',
  'Sealeo',
  'Seedot',
  'Serperior',
  'Servine',
  'Sharpedo',
  'Shelgon',
  'Shellder',
  'Shelmet',
  'Shieldon',
  'Shiftry',
  'Shiinotic',
  'Shinx',
  'Shuckle',
  'Shuppet',
  'Skarmory',
  'Skiploom',
  'Skorupi',
  'Skuntank',
  'Slaking',
  'Slakoth',
  'Slowbro',
  'Slowking',
  'Slowpoke',
  'Sneasel',
  'Sneasler',
  'Snivy',
  'Snorlax',
  'Snorunt',
  'Snover',
  'Snubbull',
  'Solosis',
  'Spheal',
  'Spoink',
  'Squirtle',
  'Stantler',
  'Staraptor',
  'Staravia',
  'Starly',
  'Starmie',
  'Staryu',
  'Steelix',
  'Stufful',
  'Stunky',
  'Sudowoodo',
  'Suicune',
  'Swablu',
  'Swampert',
  'Swanna',
  'Swellow',
  'Swinub',
  'Taillow',
  'Talonflame',
  'Tangela',
  'Tangrowth',
  'Teddiursa',
  'Tentacool',
  'Tentacruel',
  'Tepig',
  'Throh',
  'Thundurus',
  'Timburr',
  'Tirtouga',
  'Torchic',
  'Tornadus',
  'Torterra',
  'Totodile',
  'Toucannon',
  'Toxicroak',
  'Tranquill',
  'Trapinch',
  'Treecko',
  'Trevenant',
  'Trubbish',
  'Trumbeak',
  'Turtwig',
  'Typhlosion',
  'Tyranitar',
  'Tyrantrum',
  'Tyrunt',
  'Unfezant',
  'Ursaluna',
  'Ursaring',
  'Venipede',
  'Venomoth',
  'Venonat',
  'Venusaur',
  'Vibrava',
  'Victreebel',
  'Vigoroth',
  'Vikavolt',
  'Vileplume',
  'Voltorb',
  'Vulpix',
  'Wailmer',
  'Wailord',
  'Walrein',
  'Wartortle',
  'Watchog',
  'Weavile',
  'Weedle',
  'Weepinbell',
  'Weezing',
  'Whirlipede',
  'Whiscash',
  'Whismur',
  'Wobbuffet',
  'Wooper',
  'Xatu',
  'Yamask',
  'Zapdos',
  'Zebstrika',
  'Zigzagoon',
  'Zubat',
  'Zweilous'
];

export const MEGA_CAPABLE_SPECIES = [
  'Abomasnow',
  'Absol',
  'Aerodactyl',
  'Aggron',
  'Alakazam',
  'Altaria',
  'Ampharos',
  'Audino',
  'Banette',
  'Beedrill',
  'Blastoise',
  'Blaziken',
  'Camerupt',
  'Charizard',
  'Diancie',
  'Dragonite',
  'Falinks',
  'Gallade',
  'Gardevoir',
  'Gengar',
  'Glalie',
  'Groudon',
  'Gyarados',
  'Heracross',
  'Houndoom',
  'Kangaskhan',
  'Kyogre',
  'Latias',
  'Latios',
  'Lopunny',
  'Lucario',
  'Malamar',
  'Manectric',
  'Mawile',
  'Medicham',
  'Metagross',
  'Mewtwo',
  'Pidgeot',
  'Pinsir',
  'Rayquaza',
  'Sableye',
  'Salamence',
  'Sceptile',
  'Scizor',
  'Sharpedo',
  'Slowbro',
  'Steelix',
  'Swampert',
  'Tyranitar',
  'Venusaur',
  'Victreebel'
];

export const GIGAMAX_CAPABLE_SPECIES = [
  'Alcremie',
  'Appletun',
  'Blastoise',
  'Butterfree',
  'Centiskorch',
  'Charizard',
  'Cinderace',
  'Coalossal',
  'Corviknight',
  'Drednaw',
  'Duraludon',
  'Eevee',
  'Flapple',
  'Garbodor',
  'Gengar',
  'Grimmsnarl',
  'Hatterene',
  'Inteleon',
  'Kingler',
  'Lapras',
  'Machamp',
  'Melmetal',
  'Meowth',
  'Orbeetle',
  'Pikachu',
  'Rillaboom',
  'Sandaconda',
  'Snorlax',
  'Toxtricity',
  'Urshifu',
  'Venusaur'
];

export const UNRELEASED_SPECIES = [
  'Alcremie',
  'Arceus',
  'Archaludon',
  'Arctovish',
  'Arctozolt',
  'Arrokuda',
  'Barraskewda',
  'Basculegion',
  'Brambleghast',
  'Bramblin',
  'Brute Bonnet',
  'Calyrex',
  'Capsakid',
  'Chewtle',
  'Chi Yu',
  'Chien Pao',
  'Copperajah',
  'Cufant',
  'Cyclizar',
  'Dottler',
  'Dracovish',
  'Dracozolt',
  'Drednaw',
  'Eiscue',
  'Farigiraf',
  'Fezandipiti',
  'Finizen',
  'Flutter Mane',
  'Glastrier',
  'Gouging Fire',
  'Great Tusk',
  'Iron Boulder',
  'Iron Bundle',
  'Iron Crown',
  'Iron Hands',
  'Iron Jugulis',
  'Iron Leaves',
  'Iron Moth',
  'Iron Thorns',
  'Iron Treads',
  'Iron Valiant',
  'Koraidon',
  'Mabosstiff',
  'Magearna',
  'Manaphy',
  'Maschiff',
  'Milcery',
  'Minior',
  'Miraidon',
  'Munkidori',
  'Ogerpon',
  'Okidogi',
  'Orbeetle',
  'Palafin',
  'Pecharunt',
  'Phione',
  'Pincurchin',
  'Pyukumuku',
  'Rabsca',
  'Raging Bolt',
  'Rellor',
  'Roaring Moon',
  'Sandy Shocks',
  'Scovillain',
  'Scream Tail',
  'Silvally',
  'Slither Wing',
  'Spectrier',
  'Squawkabilly',
  'Terapagos',
  'Ting Lu',
  'Type: Null',
  'Veluza',
  'Walking Wake',
  'Wishiwashi',
  'Wo Chien'
];

export const SHINY_UNRELEASED_SPECIES = [
  'Aegislash',
  'Alcremie',
  'Appletun',
  'Applin',
  'Arceus',
  'Archaludon',
  'Arctovish',
  'Arctozolt',
  'Arrokuda',
  'Barraskewda',
  'Basculegion',
  'Blipbug',
  'Boltund',
  'Brambleghast',
  'Bramblin',
  'Brute Bonnet',
  'Calyrex',
  'Capsakid',
  'Carkol',
  'Centiskorch',
  'Chewtle',
  'Chi Yu',
  'Chien Pao',
  'Cinderace',
  'Clobbopus',
  'Coalossal',
  'Comfey',
  'Copperajah',
  'Cosmoem',
  'Cosmog',
  'Cramorant',
  'Cufant',
  'Cyclizar',
  'Diancie',
  'Dipplin',
  'Dottler',
  'Doublade',
  'Dracovish',
  'Dracozolt',
  'Dragapult',
  'Drakloak',
  'Drednaw',
  'Dreepy',
  'Drizzile',
  'Eiscue',
  'Eldegoss',
  'Enamorus',
  'Espathra',
  'Eternatus',
  'Farigiraf',
  'Fezandipiti',
  'Finizen',
  'Flamigo',
  'Flapple',
  'Flittle',
  'Flutter Mane',
  'Frosmoth',
  'Garganacl',
  'Glastrier',
  'Glimmet',
  'Glimmora',
  'Gossifleur',
  'Gouging Fire',
  'Grafaiai',
  'Grapploct',
  'Great Tusk',
  'Greavard',
  'Hawlucha',
  'Honedge',
  'Hoopa',
  'Houndstone',
  'Hydrapple',
  'Inteleon',
  'Iron Boulder',
  'Iron Bundle',
  'Iron Crown',
  'Iron Hands',
  'Iron Jugulis',
  'Iron Leaves',
  'Iron Moth',
  'Iron Thorns',
  'Iron Treads',
  'Iron Valiant',
  'Kilowattrel',
  'Klawf',
  'Klefki',
  'Koraidon',
  'Kubfu',
  'Lunala',
  'Mabosstiff',
  'Magearna',
  'Manaphy',
  'Marshadow',
  'Maschiff',
  'Milcery',
  'Mimikyu',
  'Minior',
  'Miraidon',
  'Mr. Rime',
  'Munkidori',
  'Nacli',
  'Naclstack',
  'Naganadel',
  'Nickit',
  'Ogerpon',
  'Okidogi',
  'Orbeetle',
  'Orthworm',
  'Palafin',
  'Pecharunt',
  'Phione',
  'Pincurchin',
  'Poipole',
  'Poltchageist',
  'Pyukumuku',
  'Raboot',
  'Rabsca',
  'Raging Bolt',
  'Rellor',
  'Revavroom',
  'Roaring Moon',
  'Rolycoly',
  'Sandaconda',
  'Sandy Shocks',
  'Scorbunny',
  'Scovillain',
  'Scream Tail',
  'Shroodle',
  'Silicobra',
  'Silvally',
  'Sinistcha',
  'Sizzlipede',
  'Slither Wing',
  'Snom',
  'Sobble',
  'Solgaleo',
  'Spectrier',
  'Spidops',
  'Squawkabilly',
  'Stonjourner',
  'Tarountula',
  'Tatsugiri',
  'Terapagos',
  'Thievul',
  'Ting Lu',
  'Toedscool',
  'Toedscruel',
  'Type: Null',
  'Ursaluna',
  'Urshifu',
  'Varoom',
  'Veluza',
  'Victini',
  'Volcanion',
  'Walking Wake',
  'Wattrel',
  'Wishiwashi',
  'Wo Chien',
  'Yamper',
  'Zarude',
  'Zeraora',
  'Zygarde'
];

export const MYTHICAL_POKEMON = [
  'Mew', 'Celebi', 'Jirachi', 'Deoxys', 'Phione', 'Manaphy', 'Darkrai', 'Shaymin', 'Arceus',
  'Victini', 'Meloetta', 'Genesect', 'Keldeo', 'Diancie', 'Hoopa', 'Volcanion', 'Magearna',
  'Marshadow', 'Zeraora', 'Meltan', 'Melmetal', 'Zarude', 'Pecharunt'
];

export const LEGENDARY_POKEMON = [
  'Articuno', 'Zapdos', 'Moltres', 'Mewtwo', 'Raikou', 'Entei', 'Suicune', 'Lugia', 'Ho-Oh',
  'Regirock', 'Regice', 'Registeel', 'Latias', 'Latios', 'Kyogre', 'Groudon', 'Rayquaza',
  'Uxie', 'Mesprit', 'Azelf', 'Dialga', 'Palkia', 'Heatran', 'Regigigas', 'Giratina', 'Cresselia',
  'Cobalion', 'Terrakion', 'Virizion', 'Tornadus', 'Thundurus', 'Reshiram', 'Zekrom', 'Landorus',
  'Kyurem', 'Xerneas', 'Yveltal', 'Zygarde', 'Type: Null', 'Silvally', 'Tapu Koko', 'Tapu Lele',
  'Tapu Bulu', 'Tapu Fini', 'Cosmog', 'Cosmoem', 'Solgaleo', 'Lunala', 'Necrozma', 'Zacian',
  'Zamazenta', 'Eternatus', 'Kubfu', 'Urshifu', 'Regieleki', 'Regidrago', 'Glastrier', 'Spectrier',
  'Calyrex', 'Enamorus', 'Wo-Chien', 'Chien-Pao', 'Ting-Lu', 'Chi-Yu', 'Koraidon', 'Miraidon',
  'Okidogi', 'Munkidori', 'Fezandipiti', 'Ogerpon', 'Gouging Fire', 'Raging Bolt', 'Iron Boulder',
  'Iron Crown', 'Terapagos'
];

export const ULTRA_BEASTS = [
  'Nihilego', 'Buzzwole', 'Pheromosa', 'Xurkitree', 'Celesteela', 'Kartana', 'Guzzlord',
  'Poipole', 'Naganadel', 'Stakataka', 'Blacephalon'
];

