export const SHADOW_CAPABLE_SPECIES = [
  'Abomasnow',
  'Abra',
  'Absol',
  'Accelgor',
  'Aerodactyl',
  'Aggron',
  'Aipom',
  'Alakazam',
  'Altaria',
  'Amaura',
  'Ambipom',
  'Amoonguss',
  'Ampharos',
  'Annihilape',
  'Anorith',
  'Araquanid',
  'Arbok',
  'Arcanine',
  'Archen',
  'Archeops',
  'Armaldo',
  'Aron',
  'Articuno',
  'Aurorus',
  'Bagon',
  'Baltoy',
  'Banette',
  'Barboach',
  'Bastiodon',
  'Bayleef',
  'Beedrill',
  'Beldum',
  'Bellossom',
  'Bellsprout',
  'Bewear',
  'Bibarel',
  'Bidoof',
  'Blastoise',
  'Blaziken',
  'Blitzle',
  'Boldore',
  'Braixen',
  'Bulbasaur',
  'Bunnelby',
  'Butterfree',
  'Cacnea',
  'Cacturne',
  'Camerupt',
  'Carracosta',
  'Carvanha',
  'Caterpie',
  'Chandelure',
  'Charizard',
  'Charjabug',
  'Charmander',
  'Charmeleon',
  'Chesnaught',
  'Chespin',
  'Chikorita',
  'Chimchar',
  'Claydol',
  'Cloyster',
  'Cofagrigus',
  'Combusken',
  'Conkeldurr',
  'Corphish',
  'Cradily',
  'Cranidos',
  'Crawdaunt',
  'Cresselia',
  'Croagunk',
  'Crobat',
  'Croconaw',
  'Crustle',
  'Cubone',
  'Cyndaquil',
  'Darkrai',
  'Darmanitan',
  'Darumaka',
  'Deino',
  'Delibird',
  'Delphox',
  'Dewott',
  'Dewpider',
  'Dialga',
  'Diggersby',
  'Diglett',
  'Donphan',
  'Dragonair',
  'Dragonite',
  'Drapion',
  'Dratini',
  'Drifblim',
  'Drifloon',
  'Drilbur',
  'Drowzee',
  'Ducklett',
  'Dugtrio',
  'Duosion',
  'Dusclops',
  'Dusknoir',
  'Duskull',
  'Dwebble',
  'Ekans',
  'Electabuzz',
  'Electivire',
  'Electrike',
  'Electrode',
  'Emboar',
  'Empoleon',
  'Entei',
  'Escavalier',
  'Excadrill',
  'Exeggcute',
  'Exeggutor',
  'Exploud',
  'Farfetch’d',
  'Feebas',
  'Fennekin',
  'Feraligatr',
  'Ferroseed',
  'Ferrothorn',
  'Flaaffy',
  'Fletchinder',
  'Fletchling',
  'Flygon',
  'Foongus',
  'Forretress',
  'Froakie',
  'Frogadier',
  'Froslass',
  'Gabite',
  'Gallade',
  'Galvantula',
  'Garbodor',
  'Garchomp',
  'Gardevoir',
  'Gastly',
  'Gengar',
  'Geodude',
  'Gible',
  'Gigalith',
  'Girafarig',
  'Giratina',
  'Glalie',
  'Glameow',
  'Gligar',
  'Gliscor',
  'Gloom',
  'Golbat',
  'Golduck',
  'Golem',
  'Golett',
  'Golurk',
  'Gothita',
  'Gothitelle',
  'Gothorita',
  'Granbull',
  'Graveler',
  'Greninja',
  'Grimer',
  'Grotle',
  'Groudon',
  'Grovyle',
  'Growlithe',
  'Grubbin',
  'Grumpig',
  'Gurdurr',
  'Gyarados',
  'Hariyama',
  'Haunter',
  'Heatran',
  'Heliolisk',
  'Helioptile',
  'Hippopotas',
  'Hippowdon',
  'Hitmonchan',
  'Hitmonlee',
  'Hitmontop',
  'Ho-Oh',
  'Honchkrow',
  'Hoppip',
  'Horsea',
  'Houndoom',
  'Houndour',
  'Hydreigon',
  'Hypno',
  'Infernape',
  'Inkay',
  'Ivysaur',
  'Joltik',
  'Jumpluff',
  'Kadabra',
  'Kakuna',
  'Karrablast',
  'Kingdra',
  'Kingler',
  'Kirlia',
  'Koffing',
  'Krabby',
  'Kyogre',
  'Lairon',
  'Lampent',
  'Landorus',
  'Lapras',
  'Larvitar',
  'Latias',
  'Latios',
  'Ledian',
  'Ledyba',
  'Liepard',
  'Lileep',
  'Linoone',
  'Litwick',
  'Loudred',
  'Lugia',
  'Luxio',
  'Luxray',
  'Machamp',
  'Machoke',
  'Machop',
  'Magikarp',
  'Magmar',
  'Magmortar',
  'Magnemite',
  'Magneton',
  'Magnezone',
  'Makuhita',
  'Malamar',
  'Mamoswine',
  'Manectric',
  'Mankey',
  'Mareep',
  'Marowak',
  'Marshtomp',
  'Mawile',
  'Meganium',
  'Meowth',
  'Metagross',
  'Metang',
  'Metapod',
  'Mewtwo',
  'Mightyena',
  'Milotic',
  'Misdreavus',
  'Mismagius',
  'Moltres',
  'Monferno',
  'Morelull',
  'Mudkip',
  'Muk',
  'Murkrow',
  'Natu',
  'Nidoking',
  'Nidoqueen',
  'Nidoran♀',
  'Nidoran♂',
  'Nidorina',
  'Nidorino',
  'Ninetales',
  'Nosepass',
  'Numel',
  'Nuzleaf',
  'Obstagoon',
  'Oddish',
  'Omanyte',
  'Omastar',
  'Onix',
  'Oshawott',
  'Palkia',
  'Patrat',
  'Persian',
  'Phanpy',
  'Phantump',
  'Pidgeot',
  'Pidgeotto',
  'Pidgey',
  'Pidove',
  'Pignite',
  'Pikipek',
  'Piloswine',
  'Pineco',
  'Pinsir',
  'Piplup',
  'Politoed',
  'Poliwag',
  'Poliwhirl',
  'Poliwrath',
  'Ponyta',
  'Poochyena',
  'Porygon',
  'Porygon-Z',
  'Porygon2',
  'Primeape',
  'Prinplup',
  'Probopass',
  'Psyduck',
  'Pupitar',
  'Purrloin',
  'Purugly',
  'Quagsire',
  'Quilava',
  'Quilladin',
  'Qwilfish',
  'Raikou',
  'Ralts',
  'Rampardos',
  'Rapidash',
  'Raticate',
  'Rattata',
  'Regice',
  'Regigigas',
  'Regirock',
  'Registeel',
  'Reuniclus',
  'Rhydon',
  'Rhyhorn',
  'Rhyperior',
  'Roggenrola',
  'Sableye',
  'Salamence',
  'Samurott',
  'Sandshrew',
  'Sandslash',
  'Sawk',
  'Sceptile',
  'Scizor',
  'Scolipede',
  'Scyther',
  'Seadra',
  'Sealeo',
  'Seedot',
  'Serperior',
  'Servine',
  'Sharpedo',
  'Shelgon',
  'Shellder',
  'Shelmet',
  'Shieldon',
  'Shiftry',
  'Shiinotic',
  'Shinx',
  'Shuckle',
  'Shuppet',
  'Skarmory',
  'Skiploom',
  'Skorupi',
  'Skuntank',
  'Slaking',
  'Slakoth',
  'Slowbro',
  'Slowking',
  'Slowpoke',
  'Sneasel',
  'Sneasler',
  'Snivy',
  'Snorlax',
  'Snorunt',
  'Snover',
  'Snubbull',
  'Solosis',
  'Spheal',
  'Spoink',
  'Squirtle',
  'Stantler',
  'Staraptor',
  'Staravia',
  'Starly',
  'Starmie',
  'Staryu',
  'Steelix',
  'Stufful',
  'Stunky',
  'Sudowoodo',
  'Suicune',
  'Swablu',
  'Swampert',
  'Swanna',
  'Swellow',
  'Swinub',
  'Taillow',
  'Talonflame',
  'Tangela',
  'Tangrowth',
  'Teddiursa',
  'Tentacool',
  'Tentacruel',
  'Tepig',
  'Throh',
  'Thundurus',
  'Timburr',
  'Tirtouga',
  'Torchic',
  'Tornadus',
  'Torterra',
  'Totodile',
  'Toucannon',
  'Toxicroak',
  'Tranquill',
  'Trapinch',
  'Treecko',
  'Trevenant',
  'Trubbish',
  'Trumbeak',
  'Turtwig',
  'Typhlosion',
  'Tyranitar',
  'Tyrantrum',
  'Tyrunt',
  'Unfezant',
  'Ursaluna',
  'Ursaring',
  'Venipede',
  'Venomoth',
  'Venonat',
  'Venusaur',
  'Vibrava',
  'Victreebel',
  'Vigoroth',
  'Vikavolt',
  'Vileplume',
  'Voltorb',
  'Vulpix',
  'Wailmer',
  'Wailord',
  'Walrein',
  'Wartortle',
  'Watchog',
  'Weavile',
  'Weedle',
  'Weepinbell',
  'Weezing',
  'Whirlipede',
  'Whiscash',
  'Whismur',
  'Wobbuffet',
  'Wooper',
  'Xatu',
  'Yamask',
  'Zapdos',
  'Zebstrika',
  'Zigzagoon',
  'Zubat',
  'Zweilous'
];

export const MEGA_CAPABLE_SPECIES = [
  'Abomasnow',
  'Absol',
  'Aerodactyl',
  'Aggron',
  'Alakazam',
  'Altaria',
  'Ampharos',
  'Audino',
  'Banette',
  'Beedrill',
  'Blastoise',
  'Blaziken',
  'Camerupt',
  'Charizard',
  'Diancie',
  'Dragonite',
  'Falinks',
  'Gallade',
  'Gardevoir',
  'Gengar',
  'Glalie',
  'Groudon',
  'Gyarados',
  'Heracross',
  'Houndoom',
  'Kangaskhan',
  'Kyogre',
  'Latias',
  'Latios',
  'Lopunny',
  'Lucario',
  'Malamar',
  'Manectric',
  'Mawile',
  'Medicham',
  'Metagross',
  'Mewtwo',
  'Pidgeot',
  'Pinsir',
  'Rayquaza',
  'Sableye',
  'Salamence',
  'Sceptile',
  'Scizor',
  'Sharpedo',
  'Slowbro',
  'Steelix',
  'Swampert',
  'Tyranitar',
  'Venusaur',
  'Victreebel'
];

export const GIGAMAX_CAPABLE_SPECIES = [
  'Alcremie',
  'Appletun',
  'Blastoise',
  'Butterfree',
  'Centiskorch',
  'Charizard',
  'Cinderace',
  'Coalossal',
  'Corviknight',
  'Drednaw',
  'Duraludon',
  'Eevee',
  'Flapple',
  'Garbodor',
  'Gengar',
  'Grimmsnarl',
  'Hatterene',
  'Inteleon',
  'Kingler',
  'Lapras',
  'Machamp',
  'Melmetal',
  'Meowth',
  'Orbeetle',
  'Pikachu',
  'Rillaboom',
  'Sandaconda',
  'Snorlax',
  'Toxtricity',
  'Urshifu',
  'Venusaur'
];

export const UNRELEASED_SPECIES = [
  'Alcremie',
  'Arceus',
  'Archaludon',
  'Arctovish',
  'Arctozolt',
  'Arrokuda',
  'Barraskewda',
  'Basculegion',
  'Brambleghast',
  'Bramblin',
  'Brute Bonnet',
  'Calyrex',
  'Capsakid',
  'Chewtle',
  'Chi Yu',
  'Chien Pao',
  'Copperajah',
  'Cufant',
  'Cyclizar',
  'Dottler',
  'Dracovish',
  'Dracozolt',
  'Drednaw',
  'Eiscue',
  'Farigiraf',
  'Fezandipiti',
  'Finizen',
  'Flutter Mane',
  'Glastrier',
  'Gouging Fire',
  'Great Tusk',
  'Iron Boulder',
  'Iron Bundle',
  'Iron Crown',
  'Iron Hands',
  'Iron Jugulis',
  'Iron Leaves',
  'Iron Moth',
  'Iron Thorns',
  'Iron Treads',
  'Iron Valiant',
  'Koraidon',
  'Mabosstiff',
  'Magearna',
  'Manaphy',
  'Maschiff',
  'Milcery',
  'Minior',
  'Miraidon',
  'Munkidori',
  'Ogerpon',
  'Okidogi',
  'Orbeetle',
  'Palafin',
  'Pecharunt',
  'Phione',
  'Pincurchin',
  'Pyukumuku',
  'Rabsca',
  'Raging Bolt',
  'Rellor',
  'Roaring Moon',
  'Sandy Shocks',
  'Scovillain',
  'Scream Tail',
  'Silvally',
  'Slither Wing',
  'Spectrier',
  'Squawkabilly',
  'Terapagos',
  'Ting Lu',
  'Type: Null',
  'Veluza',
  'Vivillon (Modern)',
  'Vivillon (Pokeball)',
  'Walking Wake',
  'Wishiwashi',
  'Wo Chien'
];

export const SHINY_UNRELEASED_SPECIES = [
  'Aegislash',
  'Alcremie',
  'Appletun',
  'Applin',
  'Arceus',
  'Archaludon',
  'Arctovish',
  'Arctozolt',
  'Arrokuda',
  'Barraskewda',
  'Basculegion',
  'Blipbug',
  'Boltund',
  'Brambleghast',
  'Bramblin',
  'Brute Bonnet',
  'Calyrex',
  'Capsakid',
  'Carkol',
  'Centiskorch',
  'Chewtle',
  'Chi Yu',
  'Chien Pao',
  'Cinderace',
  'Clobbopus',
  'Coalossal',
  'Comfey',
  'Copperajah',
  'Cosmoem',
  'Cosmog',
  'Cramorant',
  'Cufant',
  'Cyclizar',
  'Diancie',
  'Dipplin',
  'Dottler',
  'Doublade',
  'Dracovish',
  'Dracozolt',
  'Dragapult',
  'Drakloak',
  'Drednaw',
  'Dreepy',
  'Drizzile',
  'Eiscue',
  'Eldegoss',
  'Enamorus',
  'Espathra',
  'Eternatus',
  'Farigiraf',
  'Fezandipiti',
  'Finizen',
  'Flamigo',
  'Flapple',
  'Flittle',
  'Flutter Mane',
  'Frosmoth',
  'Garganacl',
  'Glastrier',
  'Glimmet',
  'Glimmora',
  'Gossifleur',
  'Gouging Fire',
  'Grafaiai',
  'Grapploct',
  'Great Tusk',
  'Greavard',
  'Hawlucha',
  'Honedge',
  'Hoopa',
  'Houndstone',
  'Hydrapple',
  'Inteleon',
  'Iron Boulder',
  'Iron Bundle',
  'Iron Crown',
  'Iron Hands',
  'Iron Jugulis',
  'Iron Leaves',
  'Iron Moth',
  'Iron Thorns',
  'Iron Treads',
  'Iron Valiant',
  'Kilowattrel',
  'Klawf',
  'Klefki',
  'Koraidon',
  'Kubfu',
  'Lunala',
  'Mabosstiff',
  'Magearna',
  'Manaphy',
  'Marshadow',
  'Maschiff',
  'Milcery',
  'Mimikyu',
  'Minior',
  'Miraidon',
  'Mr. Rime',
  'Munkidori',
  'Nacli',
  'Naclstack',
  'Naganadel',
  'Nickit',
  'Ogerpon',
  'Okidogi',
  'Orbeetle',
  'Orthworm',
  'Palafin',
  'Pecharunt',
  'Phione',
  'Pincurchin',
  'Poipole',
  'Poltchageist',
  'Pyukumuku',
  'Raboot',
  'Rabsca',
  'Raging Bolt',
  'Rellor',
  'Revavroom',
  'Roaring Moon',
  'Rolycoly',
  'Sandaconda',
  'Sandy Shocks',
  'Scorbunny',
  'Scovillain',
  'Scream Tail',
  'Shroodle',
  'Silicobra',
  'Silvally',
  'Sinistcha',
  'Sizzlipede',
  'Slither Wing',
  'Snom',
  'Sobble',
  'Solgaleo',
  'Spectrier',
  'Spidops',
  'Squawkabilly',
  'Stonjourner',
  'Tarountula',
  'Tatsugiri',
  'Terapagos',
  'Thievul',
  'Ting Lu',
  'Toedscool',
  'Toedscruel',
  'Type: Null',
  'Ursaluna',
  'Urshifu',
  'Varoom',
  'Veluza',
  'Victini',
  'Vivillon (Pokeball)',
  'Volcanion',
  'Walking Wake',
  'Wattrel',
  'Wishiwashi',
  'Wo Chien',
  'Yamper',
  'Zarude',
  'Zeraora',
  'Zygarde'
];
export const MYTHICAL_POKEMON = [
  'Mew', 'Celebi', 'Jirachi', 'Deoxys', 'Phione', 'Manaphy', 'Darkrai', 'Shaymin', 'Arceus',
  'Victini', 'Meloetta', 'Genesect', 'Keldeo', 'Diancie', 'Hoopa', 'Volcanion', 'Magearna',
  'Marshadow', 'Zeraora', 'Meltan', 'Melmetal', 'Zarude', 'Pecharunt'
];

export const LEGENDARY_POKEMON = [
  'Articuno', 'Zapdos', 'Moltres', 'Mewtwo', 'Raikou', 'Entei', 'Suicune', 'Lugia', 'Ho-Oh',
  'Regirock', 'Regice', 'Registeel', 'Latias', 'Latios', 'Kyogre', 'Groudon', 'Rayquaza',
  'Uxie', 'Mesprit', 'Azelf', 'Dialga', 'Palkia', 'Heatran', 'Regigigas', 'Giratina', 'Cresselia',
  'Cobalion', 'Terrakion', 'Virizion', 'Tornadus', 'Thundurus', 'Reshiram', 'Zekrom', 'Landorus',
  'Kyurem', 'Xerneas', 'Yveltal', 'Zygarde', 'Type: Null', 'Silvally', 'Tapu Koko', 'Tapu Lele',
  'Tapu Bulu', 'Tapu Fini', 'Cosmog', 'Cosmoem', 'Solgaleo', 'Lunala', 'Necrozma', 'Zacian',
  'Zamazenta', 'Eternatus', 'Kubfu', 'Urshifu', 'Regieleki', 'Regidrago', 'Glastrier', 'Spectrier',
  'Calyrex', 'Enamorus', 'Wo-Chien', 'Chien-Pao', 'Ting-Lu', 'Chi-Yu', 'Koraidon', 'Miraidon',
  'Okidogi', 'Munkidori', 'Fezandipiti', 'Ogerpon', 'Gouging Fire', 'Raging Bolt', 'Iron Boulder',
  'Iron Crown', 'Terapagos'
];

export const ULTRA_BEASTS = [
  'Nihilego', 'Buzzwole', 'Pheromosa', 'Xurkitree', 'Celesteela', 'Kartana', 'Guzzlord',
  'Poipole', 'Naganadel', 'Stakataka', 'Blacephalon'
];

export const EVOLVES_FROM: Record<string, string> = {
  // Gen 1
  'Ivysaur': 'Bulbasaur',
  'Venusaur': 'Ivysaur',
  'Charmeleon': 'Charmander',
  'Charizard': 'Charmeleon',
  'Wartortle': 'Squirtle',
  'Blastoise': 'Wartortle',
  'Metapod': 'Caterpie',
  'Butterfree': 'Metapod',
  'Kakuna': 'Weedle',
  'Beedrill': 'Kakuna',
  'Pidgeotto': 'Pidgey',
  'Pidgeot': 'Pidgeotto',
  'Raticate': 'Rattata',
  'Fearow': 'Spearow',
  'Arbok': 'Ekans',
  'Raichu': 'Pikachu',
  'Pikachu': 'Pichu',
  'Sandslash': 'Sandshrew',
  'Nidorina': 'Nidoran♀',
  'Nidoqueen': 'Nidorina',
  'Nidorino': 'Nidoran♂',
  'Nidoking': 'Nidorino',
  'Clefairy': 'Cleffa',
  'Clefable': 'Clefairy',
  'Jigglypuff': 'Igglybuff',
  'Wigglytuff': 'Jigglypuff',
  'Golbat': 'Zubat',
  'Crobat': 'Golbat',
  'Gloom': 'Oddish',
  'Vileplume': 'Gloom',
  'Bellossom': 'Gloom',
  'Parasect': 'Paras',
  'Venomoth': 'Venonat',
  'Dugtrio': 'Diglett',
  'Persian': 'Meowth',
  'Perrserker': 'Meowth',
  'Golduck': 'Psyduck',
  'Primeape': 'Mankey',
  'Annihilape': 'Primeape',
  'Arcanine': 'Growlithe',
  'Poliwhirl': 'Poliwag',
  'Poliwrath': 'Poliwhirl',
  'Politoed': 'Poliwhirl',
  'Kadabra': 'Abra',
  'Alakazam': 'Kadabra',
  'Machoke': 'Machop',
  'Machamp': 'Machoke',
  'Weepinbell': 'Bellsprout',
  'Tentacruel': 'Tentacool',
  'Graveler': 'Geodude',
  'Golem': 'Graveler',
  'Rapidash': 'Ponyta',
  'Slowbro': 'Slowpoke',
  'Slowking': 'Slowpoke',
  'Magneton': 'Magnemite',
  'Magnezone': 'Magneton',
  'Sirfetch\'d': 'Farfetch\'d',
  'Dodrio': 'Doduo',
  'Dewgong': 'Seel',
  'Muk': 'Grimer',
  'Haunter': 'Gastly',
  'Gengar': 'Haunter',
  'Steelix': 'Onix',
  'Hypno': 'Drowzee',
  'Kingler': 'Krabby',
  'Electrode': 'Voltorb',
  'Exeggutor': 'Exeggcute',
  'Marowak': 'Cubone',
  'Hitmonlee': 'Tyrogue',
  'Hitmonchan': 'Tyrogue',
  'Hitmontop': 'Tyrogue',
  'Lickilicky': 'Lickitung',
  'Weezing': 'Koffing',
  'Rhydon': 'Rhyhorn',
  'Rhyperior': 'Rhydon',
  'Chansey': 'Happiny',
  'Blissey': 'Chansey',
  'Tangrowth': 'Tangela',
  'Seadra': 'Horsea',
  'Kingdra': 'Seadra',
  'Seaking': 'Goldeen',
  'Starmie': 'Staryu',
  'Mr. Mr. Mr. Mr. Mr. Mime': 'Mime Jr.', // Mr. Mime: Mime Jr.
  'Mr. Rime': 'Mr. Mime',
  'Scizor': 'Scyther',
  'Kleavor': 'Scyther',
  'Jynx': 'Smoochum',
  'Electabuzz': 'Elekid',
  'Electivire': 'Electabuzz',
  'Magmar': 'Magby',
  'Magmortar': 'Magmar',
  'Gyarados': 'Magikarp',
  'Vaporeon': 'Eevee',
  'Jolteon': 'Eevee',
  'Flareon': 'Eevee',
  'Espeon': 'Eevee',
  'Umbreon': 'Eevee',
  'Leafeon': 'Eevee',
  'Glaceon': 'Eevee',
  'Sylveon': 'Eevee',
  'Porygon2': 'Porygon',
  'Porygon-Z': 'Porygon2',
  'Omastar': 'Omanyte',
  'Kabutops': 'Kabuto',
  'Snorlax': 'Munchlax',
  'Dragonair': 'Dratini',
  'Dragonite': 'Dragonair',

  // Gen 2
  'Bayleef': 'Chikorita',
  'Meganium': 'Bayleef',
  'Quilava': 'Cyndaquil',
  'Typhlosion': 'Quilava',
  'Croconaw': 'Totodile',
  'Feraligatr': 'Croconaw',
  'Furret': 'Sentret',
  'Noctowl': 'Hoothoot',
  'Ledian': 'Ledyba',
  'Ariados': 'Spinarak',
  'Lanturn': 'Chinchou',
  'Togetic': 'Togepi',
  'Togekiss': 'Togetic',
  'Xatu': 'Natu',
  'Flaaffy': 'Mareep',
  'Ampharos': 'Flaaffy',
  'Azumarill': 'Marill',
  'Marill': 'Azurill',
  'Sudowoodo': 'Bonsly',
  'Jumpluff': 'Skiploom',
  'Skiploom': 'Hoppip',
  'Sunflora': 'Sunkern',
  'Quagsire': 'Wooper',
  'Wobbuffet': 'Wynaut',
  'Farigiraf': 'Girafarig',
  'Forretress': 'Pineco',
  'Dudunsparce': 'Dunsparce',
  'Granbull': 'Snubbull',
  'Ursaring': 'Teddiursa',
  'Ursaluna': 'Ursaring',
  'Magcargo': 'Slugma',
  'Piloswine': 'Swinub',
  'Mamoswine': 'Piloswine',
  'Octillery': 'Remoraid',
  'Mantine': 'Mantyke',
  'Houndoom': 'Houndour',
  'Donphan': 'Phanpy',
  'Pupitar': 'Larvitar',
  'Tyranitar': 'Pupitar',

  // Gen 3
  'Grovyle': 'Treecko',
  'Sceptile': 'Grovyle',
  'Combusken': 'Torchic',
  'Blaziken': 'Combusken',
  'Marshtomp': 'Mudkip',
  'Swampert': 'Marshtomp',
  'Mightyena': 'Poochyena',
  'Linoone': 'Zigzagoon',
  'Obstagoon': 'Linoone',
  'Beautifly': 'Silcoon',
  'Silcoon': 'Wurmple',
  'Dustox': 'Cascoon',
  'Cascoon': 'Wurmple',
  'Lombre': 'Lotad',
  'Ludicolo': 'Lombre',
  'Nuzleaf': 'Seedot',
  'Shiftry': 'Nuzleaf',
  'Swellow': 'Taillow',
  'Pelipper': 'Wingull',
  'Kirlia': 'Ralts',
  'Gardevoir': 'Kirlia',
  'Gallade': 'Kirlia',
  'Masquerain': 'Surskit',
  'Breloom': 'Shroomish',
  'Vigoroth': 'Slakoth',
  'Slaking': 'Vigoroth',
  'Ninjask': 'Nincada',
  'Shedinja': 'Nincada',
  'Loudred': 'Whismur',
  'Exploud': 'Loudred',
  'Hariyama': 'Makuhita',
  'Delcatty': 'Skitty',
  'Lairon': 'Aron',
  'Aggron': 'Lairon',
  'Medicham': 'Meditite',
  'Manectric': 'Electrike',
  'Roselia': 'Budew',
  'Roserade': 'Roselia',
  'Swalot': 'Gulpin',
  'Sharpedo': 'Carvanha',
  'Wailord': 'Wailmer',
  'Camerupt': 'Numel',
  'Grumpig': 'Spoink',
  'Vibrava': 'Trapinch',
  'Flygon': 'Vibrava',
  'Cacturne': 'Cacnea',
  'Altaria': 'Swablu',
  'Crawdaunt': 'Corphish',
  'Claydol': 'Baltoy',
  'Cradily': 'Lileep',
  'Armaldo': 'Anorith',
  'Milotic': 'Feebas',
  'Banette': 'Shuppet',
  'Dusclops': 'Duskull',
  'Dusknoir': 'Dusclops',
  'Chimecho': 'Chingling',
  'Glalie': 'Snorunt',
  'Froslass': 'Snorunt',
  'Sealeo': 'Spheal',
  'Walrein': 'Sealeo',
  'Huntail': 'Clamperl',
  'Gorebyss': 'Clamperl',
  'Shelgon': 'Bagon',
  'Salamence': 'Shelgon',
  'Metang': 'Beldum',
  'Metagross': 'Metang',

  // Gen 4
  'Grotle': 'Turtwig',
  'Torterra': 'Grotle',
  'Monferno': 'Chimchar',
  'Infernape': 'Monferno',
  'Prinplup': 'Piplup',
  'Empoleon': 'Prinplup',
  'Staravia': 'Starly',
  'Staraptor': 'Staravia',
  'Bibarel': 'Bidoof',
  'Kricketune': 'Kricketot',
  'Luxio': 'Shinx',
  'Luxray': 'Luxio',
  'Rampardos': 'Cranidos',
  'Bastiodon': 'Shieldon',
  'Wormadam': 'Burmy',
  'Mothim': 'Burmy',
  'Vespiquen': 'Combee',
  'Floatzel': 'Buizel',
  'Cherrim': 'Cherubi',
  'Gastrodon': 'Shellos',
  'Ambipom': 'Aipom',
  'Drifblim': 'Drifloon',
  'Lopunny': 'Buneary',
  'Mismagius': 'Misdreavus',
  'Honchkrow': 'Murkrow',
  'Purugly': 'Glameow',
  'Skuntank': 'Stunky',
  'Bronzong': 'Bronzor',
  'Lucario': 'Riolu',
  'Hippowdon': 'Hippopotas',
  'Drapion': 'Skorupi',
  'Toxicroak': 'Croagunk',
  'Lumineon': 'Finneon',
  'Abomasnow': 'Snover',
  'Weavile': 'Sneasel',
  'Sneasler': 'Sneasel',
  'Yanmega': 'Yanma',
  'Gliscor': 'Gligar',

  // Gen 5
  'Servine': 'Snivy',
  'Serperior': 'Servine',
  'Pignite': 'Tepig',
  'Emboar': 'Pignite',
  'Dewott': 'Oshawott',
  'Samurott': 'Dewott',
  'Watchog': 'Patrat',
  'Herdier': 'Lillipup',
  'Stoutland': 'Herdier',
  'Liepard': 'Purrloin',
  'Simisage': 'Pansage',
  'Simisear': 'Pansear',
  'Simipour': 'Panpour',
  'Musharna': 'Munna',
  'Tranquill': 'Pidove',
  'Unfezant': 'Tranquill',
  'Zebstrika': 'Blitzle',
  'Boldore': 'Roggenrola',
  'Gigalith': 'Boldore',
  'Swoobat': 'Woobat',
  'Excadrill': 'Drilbur',
  'Gurdurr': 'Timburr',
  'Conkeldurr': 'Gurdurr',
  'Palpitoad': 'Tympole',
  'Seismitoad': 'Palpitoad',
  'Swadloon': 'Sewaddle',
  'Leavanny': 'Swadloon',
  'Whimsicott': 'Cottonee',
  'Lilligant': 'Petilil',
  'Krokorok': 'Sandile',
  'Krookodile': 'Krokorok',
  'Darmanitan': 'Darumaka',
  'Crustle': 'Dwebble',
  'Scrafty': 'Scraggy',
  'Cofagrigus': 'Yamask',
  'Carracosta': 'Tirtouga',
  'Archeops': 'Archen',
  'Garbodor': 'Trubbish',
  'Zoroark': 'Zorua',
  'Cinccino': 'Minccino',
  'Gothorita': 'Gothita',
  'Gothitelle': 'Gothorita',
  'Duosion': 'Solosis',
  'Reuniclus': 'Duosion',
  'Swanna': 'Ducklett',
  'Vanillish': 'Vanillite',
  'Vanilluxe': 'Vanillish',
  'Sawsbuck': 'Deerling',
  'Escavalier': 'Karrablast',
  'Amoonguss': 'Foongus',
  'Jellicent': 'Frillish',
  'Galvantula': 'Joltik',
  'Ferrothorn': 'Ferroseed',
  'Klang': 'Klink',
  'Klinklang': 'Klang',
  'Eelektrik': 'Tynamo',
  'Eelektross': 'Eelektrik',
  'Beheeyem': 'Elgyem',
  'Lampent': 'Litwick',
  'Chandelure': 'Lampent',
  'Fraxure': 'Axew',
  'Haxorus': 'Fraxure',
  'Beartic': 'Cubchoo',
  'Accelgor': 'Shelmet',
  'Mienshao': 'Mienfoo',
  'Golurk': 'Golett',
  'Bisharp': 'Pawniard',
  'Kingambit': 'Bisharp',
  'Braviary': 'Rufflet',
  'Mandibuzz': 'Vullaby',
  'Zweilous': 'Deino',
  'Hydreigon': 'Zweilous',
  'Volcarona': 'Larvesta',

  // Gen 6
  'Quilladin': 'Chespin',
  'Chesnaught': 'Quilladin',
  'Braixen': 'Fennekin',
  'Delphox': 'Braixen',
  'Frogadier': 'Froakie',
  'Greninja': 'Frogadier',
  'Diggersby': 'Bunnelby',
  'Fletchinder': 'Fletchling',
  'Talonflame': 'Fletchinder',
  'Spewpa': 'Scatterbug',
  'Vivillon': 'Spewpa',
  'Pyroar': 'Litleo',
  'Floette': 'Flabebe',
  'Florges': 'Floette',
  'Gogoat': 'Skiddo',
  'Pangoro': 'Pancham',
  'Meowstic': 'Espurr',
  'Doublade': 'Honedge',
  'Aegislash': 'Doublade',
  'Aromatisse': 'Spritzee',
  'Slurpuff': 'Swirlix',
  'Malamar': 'Inkay',
  'Barbaracle': 'Binacle',
  'Dragalge': 'Skrelp',
  'Clawitzer': 'Clauncher',
  'Heliolisk': 'Helioptile',
  'Tyrantrum': 'Tyrunt',
  'Aurorus': 'Amaura',
  'Sliggoo': 'Goomy',
  'Goodra': 'Sliggoo',
  'Trevenant': 'Phantump',
  'Gourgeist': 'Pumpkaboo',
  'Avalugg': 'Bergmite',
  'Noivern': 'Noibat',

  // Gen 7
  'Dartrix': 'Rowlet',
  'Decidueye': 'Dartrix',
  'Torracat': 'Litten',
  'Incineroar': 'Torracat',
  'Brionne': 'Popplio',
  'Primarina': 'Brionne',
  'Trumbeak': 'Pikipek',
  'Toucannon': 'Trumbeak',
  'Gumshoos': 'Yungoos',
  'Charjabug': 'Grubbin',
  'Vikavolt': 'Charjabug',
  'Crabominable': 'Crabrawler',
  'Ribombee': 'Cutiefly',
  'Lycanroc': 'Rockruff',
  'Toxapex': 'Mareanie',
  'Mudsdale': 'Mudbray',
  'Araquanid': 'Dewpider',
  'Lurantis': 'Fomantis',
  'Shiinotic': 'Morelull',
  'Salazzle': 'Salandit',
  'Bewear': 'Stufful',
  'Steenee': 'Bounsweet',
  'Tsareena': 'Steenee',
  'Golisopod': 'Wimpod',
  'Palossand': 'Sandygast',
  'Silvally': 'Type: Null',
  'Hakamo-o': 'Jangmo-o',
  'Kommo-o': 'Hakamo-o',
  'Cosmoem': 'Cosmog',
  'Solgaleo': 'Cosmoem',
  'Lunala': 'Cosmoem',
  'Melmetal': 'Meltan',

  // Gen 8
  'Thwackey': 'Grookey',
  'Rillaboom': 'Thwackey',
  'Raboot': 'Scorbunny',
  'Cinderace': 'Raboot',
  'Drizzile': 'Sobble',
  'Inteleon': 'Drizzile',
  'Greedent': 'Skwovet',
  'Corvisquire': 'Rookidee',
  'Corviknight': 'Corvisquire',
  'Dottler': 'Blipbug',
  'Orbeetle': 'Dottler',
  'Thievul': 'Nickit',
  'Eldegoss': 'Gossifleur',
  'Dubwool': 'Wooloo',
  'Drednaw': 'Chewtle',
  'Boltund': 'Yamper',
  'Carkol': 'Rolycoly',
  'Coalossal': 'Carkol',
  'Flapple': 'Applin',
  'Appletun': 'Applin',
  'Dipplin': 'Applin',
  'Hydrapple': 'Dipplin',
  'Sandaconda': 'Silicobra',
  'Barraskewda': 'Arrokuda',
  'Toxtricity': 'Toxel',
  'Centiskorch': 'Sizzlipede',
  'Grapploct': 'Clobbopus',
  'Polteageist': 'Sinistea',
  'Hattrem': 'Hatenna',
  'Hatterene': 'Hattrem',
  'Morgrem': 'Impidimp',
  'Grimmsnarl': 'Morgrem',
  'Alcremie': 'Milcery',
  'Frosmoth': 'Snom',
  'Copperajah': 'Cufant',
  'Drakloak': 'Dreepy',
  'Dragapult': 'Drakloak',

  // Gen 9
  'Floragato': 'Sprigatito',
  'Meowscarada': 'Floragato',
  'Crocalor': 'Fuecoco',
  'Skeledirge': 'Crocalor',
  'Quaxwell': 'Quaxly',
  'Quaquaval': 'Quaxwell',
  'Oinkologne': 'Lechonk',
  'Lokix': 'Nymble',
  'Pawmo': 'Pawmi',
  'Pawmot': 'Pawmo',
  'Maushold': 'Tandemaus',
  'Dachsbun': 'Fidough',
  'Dolliv': 'Smoliv',
  'Arboliva': 'Dolliv',
  'Naclstack': 'Nacli',
  'Garganacl': 'Naclstack',
  'Armarouge': 'Charcadet',
  'Ceruledge': 'Charcadet',
  'Bellibolt': 'Tadbulb',
  'Kilowattrel': 'Wattrel',
  'Mabosstiff': 'Maschiff',
  'Grafaiai': 'Shroodle',
  'Scovillain': 'Capsakid',
  'Rabsca': 'Rellor',
  'Espathra': 'Flittle',
  'Tinkatuff': 'Tinkatink',
  'Tinkaton': 'Tinkatuff',
  'Wugtrio': 'Wiglett',
  'Palafin': 'Finizen',
  'Revavroom': 'Varoom',
  'Gholdengo': 'Gimmighoul',
  'Arctibax': 'Frigibax',
  'Baxcalibur': 'Arctibax'
};

export const MODAL_FORMS_SPECIES = ['Unown', 'Vivillon', 'Spinda', 'Furfrou'];

